// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
       seed: 'node prisma/seed.js',
  },
  datasource: {
    url: "postgresql://postgres:chaymae2002@localhost:5433/gestion_contact_ag?schema=public"
  },
});
